# This section declares settings for the server.
[server]
host = "127.0.0.1"        # server host
port = 8080             # server port

# This section declares setting for the database.
[database]
file = "recommender/db/gorse.db"  # database file

# This section declares settings for recommendation.
[recommend]
model = "knn_implicit"  # recommendation model
cache_size = 100        # the number of cached recommendations
update_threshold = 10   # update model when more than 10 ratings are added
check_period = 1        # check for update every one minute
similarity = "implicit" # similarity metric for neighbors

# This section declares hyperparameters for the recommendation model.
[params]
